---
# vars file for linux
module_imuxsock: 'module(load="imuxsock" SysSock.Use="off")'
module_imjournal: 'module(load="imjournal" UsePid="system" StateFile="imjournal.state")'
work_location: "/var/lib/rsyslog"

rules:
  messages: '*.info;mail.none;authpriv.none;cron.none                /var/log/messages'
  authpriv: 'authpriv.*                                              /var/log/secure'
  mail: 'mail.*                                                  -/var/log/maillog'
  cron: 'cron.*                                                  /var/log/cron'
  emergency: '*.emerg                                                 :omusrmsg:*'
  critical: 'uucp,news.crit                                          /var/log/spooler'
  boot: 'local7.*                                                /var/log/boot.log'

kopts: ["console=tty0", "console=ttyS0,115200n8", "net.ifnames=0", "rd.blacklist=nouveau","nvme_core.io_timeout=4294967295","crash kernel=auto", "ipv6.disable=1"] 
grub_timeout: 0
grub_default: "saved"
grub_enable_blscfg: "true"

# Example for linux-system-roles.bootloader role
bootloader_settings:
  - kernel:
      path: /boot/vmlinuz-4.18.0-553.16.1.el8_10.x86_64
    options:
      - name: console
        value: tty0
        state: present
      - name: console
        value: ttyS0,115200n8 
        state: present
      - name: net.ifnames
        value: 0
        state: present
      - name: rd.blacklist
        value: nouveau
        state: present
      - name: nvme_core.io_timeout
        value: 4294967295
        state: present
      - name: kernel
        value: auto
        state: present
      - name: GRUB_CMDLINE_LINUX
        value: 'ipv6.disable=1'
        state: present



