---
- name: Apply rsyslog configuration
  template:
    src: templates/rsyslog.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: u=rw,g=r,u=r

- name: Make sure ipv6 is disabled in the kernel options in GRUB.
  ansible.builtin.replace:
    path: /etc/default/grub
    regexp: 'ipv6.disable=1'
    replace: ''
