---
# tasks file for linux
- name: Enforce linux host configuration
  hosts: linux
  tasks:
    - name: Apply rsyslog configuration
      src: templates/rsyslog.j2
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: u=rw,g=r,u=r

