---
# tasks file for windows
- name: Gather facts about windows
  debug:
    var: hostvars[inventory_hostname]

- name: Check which services are running on the server
  ansible.windows.win_service_info:
  register: service_info

- name: Display all services
  debug:
    var: service_info

- name: Ensure that NETBIOS is not running and disabled. 
  ansible.windows.win_service:
    name: "TCP/IP NetBIOS Helper"
    state: stopped
    start_mode: disabled

- name: Ensure the Firewall is running.
  community.windows.win_firewall:
    state: enabled
    profiles:
    - Domain
    - Private
    - Public
