---
# tasks file for windows
- name: Gather facts about windows
  debug:
    var: hostvars[inventory_hostname]

- name: Check which services are running on the server
  ansible.windows.win_service_info:
  register: service_info

- name: Display all services
  debug:
    var: service_info
